config/routes.rb
# frozen_string_literal: true

get '/projects/:project_id/kanban/board', to: 'kanban#index', as: 'project_kanban_board'

scope 'kanban' do
  get '/board', to: 'kanban#index', as: 'common_kanban_board'
  post '/set_issue_status/', to: 'kanban#set_issue_status'
  post '/:project_id/set_issue_status/', to: 'kanban#set_issue_status'
  post '/issues/', to: 'kanban#get_issues'
  post '/:project_id/issues', to: 'kanban#get_issues'
  get '/issue/:id', to: 'kanban#get_issue'
  patch '/issue/:id', to: 'kanban#patch'
end

scope 'kanban_query' do
  post '/favorites', to: 'kanban_query_enterprise#add_to_favorites', as: 'post_kanban_query_add_to_fav'
  delete '/favorites', to: 'kanban_query_enterprise#remove_from_favorites', as: 'delete_kanban_query_remove_from_fav'
end

resources :kanban_query, :except => [:show] do
  delete '/:id', to: 'kanban_query#destroy', constraints: {id: /\d+/}, as: 'kanban_query_destroy'
end

scope 'projects/:project_id/kanban_query' do
  get '/new', to: 'kanban_query#new', as: 'kanban_project_query_new'
  post '/new', to: 'kanban_query#create'
  get '/:id', to: 'kanban_query#edit', as: 'kanban_project_query_edit'
  patch '/:id', to: 'kanban_query#update', as: 'kanban_project_query_update'
  put '/:id', to: 'kanban_query#update', as: 'kanban_project_query_put'
end

scope 'kanban/issue-size' do
  match '', to: 'kanban_issue_size#edit', as: 'kanban_issue_size_create', via: [:get, :post]
  match '/:id', to: 'kanban_issue_size#edit', as: 'kanban_issue_size_edit', via: [:get, :post]
  put '/:id', to: 'kanban_issue_size#sort_order', as: 'kanban_issue_size_sort_order'
  delete '/:id', to: 'kanban_issue_size#delete', as: 'kanban_issue_size_delete'
end

scope 'issues' do
  get '/:id/status', to: 'kanban_journal_details#status', as: 'kanban_journal_details_status', constraints: IssueStatusHistoryRouteConstraint.new
  get '/:id/block-history', to: 'kanban_journal_details#block_history', as: 'kanban_journal_details_block_history'
end

app/controllers/kanban_journal_details_controller.rb
# frozen_string_literal: true

class KanbanJournalDetailsController < ApplicationController
  before_action :find_issue

  helper :issues

  def block_history
    @history_collector = KanbanIssueBlockHistoryCollector.new(@issue)

    respond_to do |format|
      format.html
    end
  end

  def status
    @statuses_collector = KanbanIssueStatusesCollector.new(@issue)

    respond_to do |format|
      format.html
    end
  end
end

app/views/kanban_journal_details/_block_history_detail.html.erb
<tr class="<%= cycle('odd', 'even') %>">
  <td>
    <%= distance_of_time_in_words(data[:duration], 0, {include_seconds: true}) %>
  </td>
  <td>
    <% if data[:start].present? %>
      <%= format_time(data[:start]) %>
    <% else %>
      -
    <% end %>
  </td>
  <td class="name">
  <% if data[:who_started].present? %>
      <%= data[:who_started] %>
    <% else %>
      -
    <% end %>
  </td>
  <td>
    <% if data[:finish].present? %>
      <%= format_time(data[:finish]) %>
    <% else %>
      -
    <% end %>
  </td>
  <td class="name">
    <% if data[:who_finished].present? %>
      <%= data[:who_finished] %>
    <% else %>
      -
    <% end %>
  </td>
  <td>
    <% if data[:block_issue_id].present? %>
      <%= link_to_issue(Issue.find(data[:block_issue_id])) %>
    <% else %>
      <%= data[:text] %>
    <% end %>
  </td>
</tr>

app/views/kanban_journal_details/_status_detail.html.erb
<% assignee = Principal.where(:id => data[:assigned_to_id]).first %>
<tr class="<%= cycle('odd', 'even') %>">
  <td class="index"><%= index + 1 %></td>
  <td class="name"><%= format_time(data[:journal].created_on) %></td>
  <td><%= issue_status.name %></td>
  <td><%= distance_of_time_in_words(data[:end_time], data[:start_time]).html_safe %></td>
  <td><%= data[:journal].user.name %></td>
  <td><%= assignee.try(:name) %></td>
</tr>

app/views/kanban_journal_details/block_history.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:label_issue_block_history) %>

<% html_title(l(:label_issue_status_plural)) %>

<% if @history_collector.history.any? %>
<table class="list">
  <thead>
    <tr>
        <th><%= l(:field_duration) %></th>
        <th><%= l(:field_start_date) %></th>
        <th><%= l(:field_author) %></th>
        <th><%= l(:field_finish_date) %></th>
        <th><%= l(:field_author) %></th>
        <th><%= l(:label_details) %></th>
    </tr>
  </thead>
  <tbody>
    <% @history_collector.history.each_with_index do |data, index| %>
      <%= render partial: 'block_history_detail', locals: { data: data } %>
    <% end %>
  </tbody>
</table>
<% if @history_collector.durations[:total].present? %>
<div>
  <%= l(:label_total_block_duration) %> &ndash;
  <%= distance_of_time_in_words(@history_collector.durations[:total], 0, {include_seconds: true}) %>
</div>
<% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/kanban_journal_details/status.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:label_issue_status) %>

<% html_title(l(:label_issue_status_plural)) %>

<% if @statuses_collector.data.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_status) %></th>
      <th><%= l(:field_duration) %></th>
      <th><%= l(:field_author) %></th>
      <th><%= l(:field_assigned_to) %></th>
  </tr></thead>
  <% @statuses_collector.data.each_with_index do |data, index| %>
    <% issue_status = IssueStatus.where(:id => data[:status_id]).first %>
    <%= render partial: 'status_detail', locals: { issue_status: issue_status, data: data, index: index } %>
  <% end %>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>