config/routes.rb
# frozen_string_literal: true

get '/projects/:project_id/kanban/board', to: 'kanban#index', as: 'project_kanban_board'

scope 'kanban' do
  get '/board', to: 'kanban#index', as: 'common_kanban_board'
  post '/set_issue_status/', to: 'kanban#set_issue_status'
  post '/:project_id/set_issue_status/', to: 'kanban#set_issue_status'
  post '/issues/', to: 'kanban#get_issues'
  post '/:project_id/issues', to: 'kanban#get_issues'
  get '/issue/:id', to: 'kanban#get_issue'
  patch '/issue/:id', to: 'kanban#patch'
end

scope 'kanban_query' do
  post '/favorites', to: 'kanban_query_enterprise#add_to_favorites', as: 'post_kanban_query_add_to_fav'
  delete '/favorites', to: 'kanban_query_enterprise#remove_from_favorites', as: 'delete_kanban_query_remove_from_fav'
end

resources :kanban_query, :except => [:show] do
  delete '/:id', to: 'kanban_query#destroy', constraints: {id: /\d+/}, as: 'kanban_query_destroy'
end

scope 'projects/:project_id/kanban_query' do
  get '/new', to: 'kanban_query#new', as: 'kanban_project_query_new'
  post '/new', to: 'kanban_query#create'
  get '/:id', to: 'kanban_query#edit', as: 'kanban_project_query_edit'
  patch '/:id', to: 'kanban_query#update', as: 'kanban_project_query_update'
  put '/:id', to: 'kanban_query#update', as: 'kanban_project_query_put'
end

scope 'kanban/issue-size' do
  match '', to: 'kanban_issue_size#edit', as: 'kanban_issue_size_create', via: [:get, :post]
  match '/:id', to: 'kanban_issue_size#edit', as: 'kanban_issue_size_edit', via: [:get, :post]
  put '/:id', to: 'kanban_issue_size#sort_order', as: 'kanban_issue_size_sort_order'
  delete '/:id', to: 'kanban_issue_size#delete', as: 'kanban_issue_size_delete'
end

scope 'issues' do
  get '/:id/status', to: 'kanban_journal_details#status', as: 'kanban_journal_details_status', constraints: IssueStatusHistoryRouteConstraint.new
  get '/:id/block-history', to: 'kanban_journal_details#block_history', as: 'kanban_journal_details_block_history'
end

app/controllers/kanban_controller.rb
# frozen_string_literal: true

class KanbanController < ApplicationController
  menu_item :redmine_kanban

  require 'json'

  include KanbanHelper
  include KanbanApiHelper
  include ProjectsHelper
  include QueriesHelper
  helper CustomFieldsHelper
  helper KanbanTranslateHelper
  helper CustomFieldsHelper


  accept_api_auth :get_issues, :get_issue

  before_action :find_optional_project,
                only: [:index, :get_issues, :set_issue_status]
  before_action :build_kanban_query,
                only: [:index, :get_issues, :set_issue_status]
  before_action :find_issue,
                only: [:set_issue_status, :get_issue, :patch]
  before_action :check_issue_updated_at,
                only: [:set_issue_status, :patch]

  def index
    @settings = get_board_settings
  end

  def get_issues
    params[:format] = :json
    respond_to do |format|
      format.html do
        render('get_issues', formats: :json, content_type: 'application/json')
      end
      format.json do
        render('get_issues', formats: :json, content_type: 'application/json')
      end
    end
  rescue StandardError => e
    api_exception(e)
  end

  def get_issue
    params[:format] = :json
    respond_to do |format|
      format.html do
        render(formats: :json, content_type: 'application/json')
      end
      format.json
    end
  end

  def set_issue_status
    raise(StandardError.new(l(:kanban_rejected_status))) unless User.current.allowed_to?(:edit_issues, @project)

      @issue.init_journal(User.current)
      @issue.safe_attributes = {status_id: params[:status_id].to_i}

      unless @issue.save
        render(json: {errors: @issue.errors.full_messages}, status: :forbidden)
        return
      end

    @items = @query.issues(limit: KanbanSettings.issues_limit)
    params[:format] = :json
    respond_to do |format|
      format.html do
        render('get_issues', formats: :json, content_type: 'application/json')
      end
      format.json do
        render('get_issues')
      end
    end
  rescue StandardError => e
    api_exception(e)
  end

  def patch
    @issue.init_journal(User.current)

    if params[:data][:block_reason]
      # if it was blocked do not change blocked_at
      @issue.blocked_at = Time.current if @issue.block_reason.nil?
      @issue.block_reason = params[:data][:block_reason].strip
    end

    @issue.blocked_at = params[:data][:blocked_at] if params[:data][:blocked_at]
    @issue.subject = params[:data][:subject].strip if params[:data][:subject]
    @issue.description = params[:data][:description].strip if params[:data][:description]

    params[:format] = :json

    unless @issue.save
      api_validation_errors(@issue)
      return
    end

    respond_to do |format|
      format.html do
        render('kanban/get_issue', formats: :json, content_type: 'application/json')
      end
      format.json
    end
  rescue StandardError => e
    api_exception(e)
  end
end

app/helpers/kanban_helper.rb
# frozen_string_literal: true

module KanbanHelper
  include QueriesHelper
  include IssuesHelper

  include ActionView::Helpers::DateHelper
  include AdvancedChecklistHelper if KanbanSettings.is_advanced_checklists_installed?


  # Renders issue parents recursively
  def render_issue_parents(issue, api, tree)
    if issue.parent.nil?
      api.parents(tree) if tree.length.positive?
    else
      parent = issue.parent
      p = {id: parent.id, subject: parent.subject}
      p[:tracker] = {id: parent.tracker_id, name: parent.tracker.name} unless parent.tracker.nil?
      p[:status] = {id: parent.status_id, name: parent.status.name, is_closed: parent.status.is_closed} unless parent.status.nil?

      p[:child] = tree if tree.length.positive?
      tree = p
      render_issue_parents(parent, api, tree)
    end
  end

  def available_statuses_tags(query)
    tags = ''.html_safe
    query.available_statuses.each do |status|
      checkbox = check_box_tag('s[]', status.id, query.has_status?(status.id), id: status.name.to_s) + " #{status.name}"
      tags << content_tag('label', checkbox, class: 'inline')
    end

    tags
  end

  def available_kanban_columns_tags(query)
    tags = ''.html_safe
    query.available_board_columns.each do |column|
      tags << content_tag(
        'label',
        check_box_tag('c[]', column.name.to_s, query.has_column?(column), id: nil) + " #{column.caption}",
        class: 'inline'
      )
    end

    tags
  end

  def to_arr(query)
    return {query_id: query.id} if query.id

    f = []
    op = {}
    v = {}
    if query.filters.present?
      query.filters.each do |field, filter|
        f << field
        op[field.to_s] = filter[:operator]
        v[field] = []
        filter[:values].each do |value|
          v[field] << value
        end
      end
    end

    r = {
      set_filter: '1',
      sort: query.sort_criteria.to_param,
      f: f,
      op: op,
      v: v,
      group_by: query.group_by,
      c: query.columns.map(&:name)
    }
    r[:s] = query.statuses.map(&:to_s) if query.respond_to?(:statuses)

    r
  end

  def user_name_or_anonymous(user)
    user.nil? ? l(:label_user_anonymous) : user.name
  end

  def transform_user(record)
    u = {
      id: record.id,
      type: record.type,
      name: user_name_or_anonymous(record)
    }
    avatar = avatar(record, {size: 40})
    u[:avatar] = avatar if avatar.length > 1

    u
  end

  def get_show_card_properties(query)
    # rubocop:disable Lint/UselessAssignment
    # rubocop:disable Style/RedundantAssignment
    show_card_properties = query.columns.map do |column|
      v = column.name
      v
    end
    # rubocop:enable Lint/UselessAssignment
    # rubocop:enable Style/RedundantAssignment
    show_card_properties
  end

  def render_issue_on_board(issue, api)
    api.id(issue.id)
    api.status(issue_kanban_column(@query, issue)) unless issue.status.nil?
    api.subject(issue.subject)
    api.block_reason(issue.kanban_issue&.block_reason)
    api.blocked_at(issue.kanban_issue&.blocked_at)
    api.updated_on(issue.updated_on)
    # end required fields

    api.updated_on(issue.updated_on) if @query.has_column?(:updated_on)
    api.subject(issue.subject) if @query.has_column?(:subject)
    api.is_private(issue.is_private?) if @query.has_column?(:is_private)
    api.created_on(issue.created_on) if @query.has_column?(:created_on)
    # @TODO
    api.author(user_name_or_anonymous(issue.author)) if @query.has_column?(:author)

    api.tracker(id: issue.tracker_id, name: issue.tracker.name) if @query.has_column?(:tracker) && !issue.tracker.nil?
    api.project(id: issue.project_id, name: issue.project.name) if @query.has_column?(:project) && !issue.project.nil?
    api.priority(id: issue.priority_id, name: issue.priority.name) if @query.has_column?(:priority) && !issue.priority.nil?
    api.category(id: issue.category_id, name: issue.category.name) if @query.has_column?(:category) && !issue.category.nil?
    api.fixed_version(id: issue.fixed_version_id, name: issue.fixed_version.name) if @query.has_column?(:fixed_version) && !issue.fixed_version.nil?

    # rubocop:disable Style/IfUnlessModifier
    if !issue.disabled_core_fields.include?('due_date') && @query.has_column?(:due_date)
      api.due_date(issue.due_date)
      api.due_date_human(issue_due_date_details(issue))
    end

    if !issue.disabled_core_fields.include?('estimated_hours') && @query.has_column?(:total_estimated_hours)
      api.total_estimated_hours(issue.total_estimated_hours)
    end

    if User.current.allowed_to?(:view_time_entries, issue.project) && @query.has_column?(:total_spent_hours)
      api.total_spent_hours(issue.total_spent_hours.round(1))
    end

    if @query.has_column?(:parent) && !issue.parent_issue_id.nil?
      render_issue_parents(issue, api, {})
    end

    if !issue.disabled_core_fields.include?('assigned_to_id') && @query.has_column?(:assigned_to) && !issue.assigned_to_id.nil?
      api.assigned_to(transform_user(issue.assigned_to))
    end
    # rubocop:enable Style/IfUnlessModifier

    api.blocked_by_issues(issue.blocked_by_issues) if issue.is_blocked_by_issues?

    if KanbanSettings.is_advanced_checklists_installed? && @query.has_column?(:questionlist) && issue.project.module_enabled?(AdvancedChecklistSettings::MODULE_NAME) \
      && respond_to?(:transform_checklist_info)
      api.question_lists(issue.questionlists.map {|checklist| transform_checklist_info(checklist)})
    end

    render_issue_tags(issue, api) if KanbanSettings.is_tags_installed? && @query.has_column?(:tags)

    api.size(id: issue.size.id, name: issue.size.name) if @query.has_column?(:kanban_issue_size) && !issue.size.nil?

  end

  def get_board_settings
    {
      id: @project&.identifier,
      query: request.GET.empty? ? to_arr(@query) : request.GET,
      statuses: format_statuses(@query),
      show_card_properties: get_show_card_properties(@query)
    }
  end

  def self.is_true(value)
    return false unless value.present?

    ['true', 'yes', 'y', '1', 1, true].include?(value)
  end

  def issue_kanban_column(query, issue)
    {
      id: issue.status_id,
      name: issue.status.name,
      is_closed: issue.status.is_closed
    }
  end
end

app/views/settings/kanban/_general.html.erb
<p>
  <label><%= l(:label_show_in_top_menu) %></label>
  <span>
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag('settings[kanban_show_in_top_menu]', 0) %>
    <%= check_box_tag('settings[kanban_show_in_top_menu]', 1, @settings['kanban_show_in_top_menu'].to_i.positive?) %>
    </span>
  </span>
</p>

<p>
  <label><%= l(:label_show_in_app_menu) %></label>
  <span>
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag('settings[kanban_show_in_app_menu]', 0) %>
      <%= check_box_tag('settings[kanban_show_in_app_menu]', 1, @settings['kanban_show_in_app_menu'].to_i.positive?) %>
    </span>
  </span>
</p>
<p>

  <label><%= l(:label_use_issue_sizes) %></label>
  <span>
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag('settings[use_kanban_issue_sizes]', 0) %>
      <%= check_box_tag('settings[use_kanban_issue_sizes]', 1, @settings['use_kanban_issue_sizes'].to_i.positive?) %>
    </span>
  </span>
</p>

<fieldset class="box">
  <legend>
    <%= toggle_checkboxes_link('#enabled_in_projects input[type=checkbox]:enabled') %><%= l(:label_project_plural) %>
  </legend>
  <div id="custom_field_project_ids" class="project-list-setting">
    <% project_ids = Project.all.select {|sub| sub.module_enabled?('kanban')}.map(&:id) %>
    <%= render_project_nested_lists(Project.all) do |p|
      content_tag('label', check_box_tag('settings[project_ids][]', p.id, project_ids.include?(p.id), id: nil) + ' ' + p)
    end %>
  </div>
  <p>
    <%= check_all_links('custom_field_project_ids') %>
  </p>
</fieldset>

app/views/settings/kanban/_index.html.erb
<% content_for(:header_tags) do %>
  <%= stylesheet_link_tag('redmine-kanban', plugin: 'redmine_kanban') %>
<% end %>

<%= render_tabs([
  {name: 'general', partial: 'settings/kanban/general', label: :label_kanban},
  {name: 'issue_size', partial: 'settings/kanban/issue_size', label: :label_issue_size},
]) %>

app/views/settings/kanban/_issue_size.html.erb
<div class="contextual">
  <%= link_to(l(:button_create), kanban_issue_size_create_path, class: 'icon icon-add') %>
</div>

<% @sizes = KanbanIssueSize.get_all_ordered %>

<% if @sizes.count == 0 %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <table class="list kanban_issue_sizes">
    <thead>
    <tr>
      <th><%= l(:field_name) %></th>
      <th>&nbsp</th>
    </tr>
    </thead>
    <tbody>
      <% for size in @sizes %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td>
            <%= size.name %>
          </td>
          <td class="buttons">
            <%= reorder_handle(size,
                               url: kanban_issue_size_sort_order_path(id: size.id),
                               param: 'order') %>
            <%= link_to(l(:button_edit),
                        kanban_issue_size_edit_path(id: size.id),
                        class: 'icon icon-edit',
                        accesskey: accesskey(:edit)) %>
            <%= link_to(l(:button_delete),
                        kanban_issue_size_delete_path(id: size.id),
                        confirm: l(:text_are_you_sure),
                        method: :delete,
                        class: 'icon icon-del') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= javascript_tag do %>
  $(function() {
    $('table.kanban_issue_sizes tbody').positionedItems();
  });
<% end %>